# Generated by Django 4.2.6 on 2023-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=8)),
                ('long_url', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
